-- {"id":95567285,"ver":"1.0.0","libVer":"1.0.0","author":"Oceaniarose, Shosetsu devs","dep":["Madara>=2.2.0"]}

return Require("Madara")("https://danmeinovel.com", {
  id = 95567285,
    name = "Danmeinovel",
      imageURL = "https://danmeinovel.com/wp-content/uploads/2017/10/logo.png",
     novelListingURLPath = "manga",
     shrinkURLNovel = "manga",
    chaptersScriptLoaded = true,
    hasSearch = true,
    searchHasOper = true,
genres = {
 "ABO",
 "Action",
 "Adventure",
 "BL",
 "Comedy",
 "Comic",
 "Cooking",
  "Danmei",
  "Drama",
  "Fantasy",
  "Historical",
 "Horror",
   "Manga",
  "Manhua",
  "Manhwa",
"Mystery",
 "Novel",
  "One shot",
"Psychological",
 "Romance",
 "School Life",
 "Sci-fi",
  "Shounen Ai",
 "Slice of Life",
  "Soft Yaoi",
   "Sports",
   "Supernatural",
     "Tragedy",
 "Webtoon",
"Yaoi" 
}
    })