-- {"id":1742321,"ver":"1.0.0","libVer":"1.0.0","author":"Lev616","dep":["Madara>=2.2.0"]}

return Require("Madara")("https://lovelyblossoms.com", {
    id = 1742321,
    name = "Lovely Blossoms",
    imageURL = "https://github.com/shosetsuorg/extensions/raw/dev/icons/SleepyTranslations.png",
    chaptersScriptLoaded = true,
    novelPageTitleSel = "div.post-title > h1",
    latestNovelSel = ".col-6.col-md-3.badge-pos-2",
    novelListingURLPath = "novel",
    shrinkURLNovel = "novel",
    searchHasOper = true,

    genres = {
        "Action",
        "Adventure",
        "Comedy",
        ["concubine-s"] = "Concubine/s",
        "Drama",
        "Fantasy",
        "Gender Bender",
        "Harem",
        "Historical",
        "isekai",
        "Josei",
        "Magic",
        ["martialarts"] = "Martial Arts",
        "Matriarchy",
        "Mature",
        "Modern",
        "Mystery",
        "Palace",
        "Psychological",
        "Reincarnation",
        "Reverse Harem",
        "Romance",
        ["schoollife"] = "School Life",
        ["scifi"] = "Sci-Fi",
        "Shoujo",
        "Shounen",
        ["sliceoflife"] = "Slice of Life",
        "Smut",
        ["strong-female-lead"] = "Strong Female Lead",
        "Supernatural",
        "System",
        "Tragedy",
        "Transmigration",
        "Yaoi",
        ["complete"] = "Completed",
        ["on-going"] = "Ongoing",
        "Canceled",
        "On Hold",
    }
})

